Fix: SystemStackError when `large_hash.slice!`
Problem
====

Calling `slice!` method of a very large hash causes a
SystemStackError` unexpectedly:

```ruby
> (1..200_000).map {|i| [i, i] }.to_h.slice!(1) ; print
SystemStackError: stack level too deep
```

This is because splat operator `*` for a large enumerable uses up the
VM's stack.

Solution
====

Rewrite `Hash#slice!` method not to use the splat operator `*`.

NOTE
====

This problem causes only in Ruby 2.1 or lower, according to [this issue](https://redmine.ruby-lang.org/issues/10440).
And Rails 5 doesn't support the versions.
So this patch might not make anything better,
but don't you feel my version looks simpler?